### ISSUE TITLE
Very good repo.

### ISSUE THREAD

**Issue by xxopenxx** [swagkarna/Defeat-Defender-V1.2#10]
Any suggestions how to make this file fud longer? Ofc people SHOULD NOT scan it with virustotal, etc.

Thanks for this repo, works great

**Comment by swagkarna** [comment]
Dont Upload sample anywhere...Dont wory i will be maintaining this project if it becomes
detectable again i will make fud

**Comment by killzone559pl** [comment]
> Dont Upload sample anywhere...Dont wory i will be maintaining this project if it becomes
> detectable again i will make fud

Nice! Is there a way to turn off the notif when you launch this script "defender is turned off" in right down corner. It's a notification from defender but still, someone can see this

**Comment by swagkarna** [comment]
> > Dont Upload sample anywhere...Dont wory i will be maintaining this project if it becomes
> > detectable again i will make fud
> 
> Nice! Is there a way to turn off the notif when you launch this script "defender is turned off" in right down corner. It's a notification from defender but still, someone can see this

I have added this feature no notification will be shown when it is disabled
