### ISSUE TITLE
Fix line: 73

### ISSUE THREAD

**Issue by aquiso** [swagkarna/Defeat-Defender-V1.2#16]
Line 73 in file: **Defeat-Defender.bat** 

should be changed to 
```batch
cd "%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup"
```
instead of 
```batch
cd "%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup^M
```

**Comment by swagkarna** [comment]
> Line 73 in file: **Defeat-Defender.bat**
> 
> should be changed to
> 
> ```batchfile
> cd "%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup"
> ```
> 
> instead of
> 
> ```batchfile
> cd "%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup^M
> ```

First download batch file on your pc and open batch file and see the code

**Comment by aquiso** [comment]
first fix your crapy code lmfao
