### ISSUE TITLE
It's dont work

### ISSUE THREAD

**Issue by WhiteWolfDD** [swagkarna/Defeat-Defender-V1.2#25]
I need to switch off the defender.

I run the **defeat-defender.bat** in admin rights, turned off only **_cloud protection_** and **_automatic sending of samples_**.
But I need to turn off **real time protection** and **tamper protection**.

Maybe I'm doing something wrong?

![изображение_2021-09-19_145420](https://user-images.githubusercontent.com/71248043/133926552-1da835a4-bf92-470f-9487-af234e144266.png)

**Comment by b4sh1t1** [comment]
run.bat file first; then put your exe url; then run Defeat-Defender.bat and reboot.

**Comment by WhiteWolfDD** [comment]
Thank you!
